# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8510aaa99e560fa9bf3fb78e989e1ee571037a6dda7139c19b2ee46885c56bf67b34b5600415abda70a8d160468655a5aa8b6978e2d67253ac16b37cdb3e7c7

test:
  secret_key_base: db5a880bef05b11b22dfa8a564ee87ece04dc95716e98977d2cf90418c23f04402070115873f55392d36024e04cb59b12440995af9524de0a57b3e508180cb05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
